apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: python-web-image
  annotations:
    iconClass: icon-python
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 3
    labels:
      app: python-web
    name: python-web
  spec:
    replicas: 1
    selector:
      app: python-web
      deploymentconfig: python-web
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: python-web
          deploymentconfig: python-web
      spec:
        containers:
        - env:
          - name: TEXT
            value: ${TEXT}
          image: jdob/python-web@sha256:09da938dd0e3cbd1f2803431745084e6e7626e95c874bbe65e70929b542cf252
          imagePullPolicy: Always
          name: python-web
          ports:
          - containerPort: 8000
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - python-web
        from:
          kind: ImageStreamTag
          name: python-web:latest
          namespace: web-test
      type: ImageChange
  status:
    availableReplicas: 1
    observedGeneration: 3
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: null
    labels:
      app: python-web
    name: python-web
  spec:
    port:
      targetPort: 8000-tcp
    to:
      kind: Service
      name: python-web
      weight: 100
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2016-10-04T20:06:22Z
        status: "True"
        type: Admitted
      routerName: router
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: python-web
    name: python-web
  spec:
    ports:
    - name: 8000-tcp
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      deploymentconfig: python-web
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
parameters:
  - name: APP_FILE
    description: DO NOT CHANGE
    value: web.py
    required: true
  - name: TEXT
    description: Text to display

